[package]
name = "tide-authorize"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]
base64 = "0.10"
futures-preview = "0.3.0-alpha.13"
http = "0.1"
rand = "0.6"
pwhash = "0.3"
tide = { git = "https://github.com/HeroicKatora/tide" }
