[package]
name = "tide-session"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

[dependencies]
tide = { git = "https://github.com/HeroicKatora/tide" }
rand = "0.6"
